version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodbcontainer
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  backend:
    image: backend
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://mongodbcontainer:27017
      - DB_NAME=sampledata
volumes:
  mongodb:

    
    