version: '3.8'
services:
  postgresql:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/db
    container_name: postgres
    environment:
      - POSTGRES_USER=ritesh7767
      - POSTGRES_PASSWORD=ritesh7767
      - POSTGRES_DB=dummy
  mongodb:
    image: mongo
    container_name: mongodbcontainer
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  backend:
    image: backend
    container_name: backend
    depends_on:
      - mongodb
      - postgresql
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://ritesh7767:ritesh7767@postgres:5432
      - DB_URL=mongodb://mongodbcontainer:27017
      - DB_NAME=sampledata
volumes:
  mongodb:
  postgresql:

    
    